spring.application.name=proposal-management

spring.datasource.url=jdbc:mysql://localhost:3309/proposals
spring.datasource.username=app
spring.datasource.password=app
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.docker.compose.lifecycle-management=start-only

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create